### ISSUE TITLE
argument must be string, not unicode

### ISSUE THREAD

**Issue by breerly** [uber/thriftrw-python#26]
Running into this with Python 2.7.3 - works with 2.7.10 just fine.

cc @blampe @abhinav 

```
ERROR:tchannel:An unexpected error has occurred from the handler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tchannel/tornado/dispatch.py", line 179, in handle_call
    b = yield request.get_body()
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/tchannel/tornado/request.py", line 136, in get_body
    body = self.serializer.deserialize_body(raw_body)
  File "/usr/local/lib/python2.7/dist-packages/tchannel/serializer/thrift.py", line 105, in deserialize_body
    return self.module.loads(self.deserialize_type, body)
  File "/usr/local/lib/python2.7/dist-packages/thriftrw/protocol/core.py", line 85, in loads
    value = self.deserialize_value(TType.STRUCT, s)
  File "/usr/local/lib/python2.7/dist-packages/thriftrw/protocol/binary.py", line 309, in deserialize_value
    return reader.read(typ)
  File "/usr/local/lib/python2.7/dist-packages/thriftrw/protocol/binary.py", line 53, in read
    return self._reader(typ)(self)
  File "/usr/local/lib/python2.7/dist-packages/thriftrw/protocol/binary.py", line 117, in read_struct
    field_type = self._byte()
  File "/usr/local/lib/python2.7/dist-packages/thriftrw/protocol/binary.py", line 76, in _byte
    return self._unpack(1, '!b')
  File "/usr/local/lib/python2.7/dist-packages/thriftrw/protocol/binary.py", line 72, in _unpack
    (result,) = struct.unpack(spec, self._read(num_bytes))
TypeError: Struct() argument 1 must be string, not unicode
INFO:tchannel:Stop Outgoing Streams because of error: Struct() argument 1 must be string, not unicode
```

Bug already filed: https://bugs.python.org/issue19099

**Comment by blampe** [comment]
Fixed in 0.3.2.
